In [1]:
import time
import DRLPDE.main

start = time.time()
model = DRLPDE.main.solvePDE('example1', 
                             savemodel='Test1A', 
                             trainingsteps=1e2,
                             method={'type':'direct'},
                             resample_every = 10)

end = time.time()
print('Time to train: {:3.0f} minutes'.format((end - start)/60))

TypeError: thePoints.TrainL2LinfLoss() missing 1 required positional argument: 'squaredlosses'

In [5]:
test

[tensor([], dtype=torch.int64),
 tensor([]),
 tensor([-0.6577]),
 tensor([-1.4361,  1.3108]),
 tensor([-0.1901,  0.3818, -0.3123]),
 tensor([ 0.9207,  1.0439, -0.2025, -0.4228]),
 tensor([ 0.3927,  1.5715,  0.3824,  0.6032, -1.0658]),
 tensor([ 0.7374,  0.6710, -0.9676, -0.6518, -0.8131, -0.8811]),
 tensor([ 1.5874, -0.2522, -1.6625, -1.5709, -1.5281, -1.4727,  0.8165]),
 tensor([-0.3417,  0.1580, -1.4939,  0.6993,  1.0436, -0.6714, -0.3181,  1.4275]),
 tensor([ 0.0281,  0.9503, -0.1693, -0.5329,  3.0040,  0.3530, -0.2851,  0.8538,
         -0.9675])]