In [1]:
import torch
import numpy as np
import time
import DRLPDE_nn


In [2]:
model = DRLPDE_nn.IncompressibleNN(5,5,2,False).to('cpu')

In [3]:
X = torch.randn((10,2), requires_grad=True)
U = model(X)

Target = DRLPDE_nn.autodiff_vB(U,X)

In [4]:
loss = torch.norm(Target, dim=1)

### Rejection sampling ###
# generate uniform( max_loss )
# Compare sample < uniform
# Then resample

check_sample = torch.rand(X.size(0), device=X.device)
resample_index = loss < check_sample

loss = torch.mean( loss )

In [6]:
loss.is_leaf

False

In [10]:
class Data(torch.utils.data.Dataset):
    
    def __init__(self, num):
        
        X = torch.randn(num,2)
        #region = close_to_region(Xold)
        
        self.location = X
        self.num_pts = num
        #self.region = region
        
    def __len__(self):
        ### How many data points are there?
        return self.num_pts
    
    def __getitem__(self, index):
        ### Gets one sample of data
        ### 
        return self.location[index,:], index


In [56]:
X = Data(10)

Batch = torch.utils.data.DataLoader(X, batch_size=2, shuffle=True)

In [61]:
for Xbatch, index in Batch:
    print(index.size())
    print(X.location[0])

torch.Size([2])
tensor([ 1.0808, -0.9571])
torch.Size([2])
tensor([ 1.0808, -0.9571])
torch.Size([2])
tensor([ 1.0808, -0.9571])
torch.Size([2])
tensor([ 1.0808, -0.9571])
torch.Size([2])
tensor([ 1.0808, -0.9571])


In [52]:
index[ torch.randn(2) < 0 ]

tensor([0])

In [39]:
torch.cat(( index, torch.tensor( [1024] , dtype=torch.int8) ))

tensor([0, 8, 0])

In [2]:
B = torch.tensor( [1024], dtype=torch.int64)

In [4]:
B = B.to('cpu')